---

- name: Install curl
  dnf:
  name: curl
  state: present
  become: true

- name: Install policycoreutils
  dnf:
  name: policycoreutils
  state: present
  become: true

- name: Install openssh-server
  name: openssh-server
  state: present
  become: true

- name: Install openssh-clients
  name: openssh-clients
  state: present
  become: true

- name: Install postfix
  name: postfix
  state: present
  become: true


