---

- name: Install curl
  yum:
    name: curl
    state: present
  become: true

- name: Install policycoreutils
  yum:
    name: policycoreutils
    state: present
  become: true

- name: Install openssh-server
  yum:
    name: openssh-server
    state: present
  become: true

- name: Install openssh-clients
  yum:
    name: openssh-clients
    state: present
  become: true

- name: Install postfix
  yum:
    name: postfix
    state: present
  become: true


