---

- name: Add the GitLab package server
  raw: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

- name: Install the GitLab package
  yum:
    name: gitlab-ce
    state: present

- name: Configure and start GitLab
  raw: gitlab-ctl reconfigure
