---

- name: Disable IPv6 on All
  command: >
    sysctl -w net.ipv6.conf.all.disable_ipv6=1

- name: Disable IPv6 on Default
  command: >
    sysctl -w net.ipv6.conf.default.disable_ipv6=1

- name: Install NTP Service
  yum:
    name: ntp
    state: present
  notify: Start ntp

- name: Install curl
  yum:
    name: curl
    state: present

- name: Install policycoreutils
  yum:
    name: policycoreutils
    state: present

- name: Install openssh-server
  yum:
    name: openssh-server
    state: present
  notify: Enable sshd
  notify: Start sshd

- name: Install openssh-clients
  yum:
    name: openssh-clients
    state: present

- name: Install postfix
  yum:
    name: postfix
    state: present
  notify: Enable postfix
  notify: Start postfix

