---

- name: Install NTP Service
  yum:
    name: ntp
    state: present
  notify: Start ntp

- name: Install curl
  yum:
    name: curl
    state: present

- name: Install openssh-clients
  yum:
    name: openssh-clients
    state: present

- name: Install postfix
  yum:
    name: postfix
    state: present
  notify: Enable postfix
  notify: Start postfix

